import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import { GridSmallBackgroundDemo } from "@/components/ui/componentPage/GridSmallBackgroundDemo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Arthur Portfolio ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen relative text-white">
          <div className="py-4">
            <GridSmallBackgroundDemo />
            <Header />
          </div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
